### PR TITLE
Add TypeScript declarations

### PR DESCRIPTION
**Pull request by Rogerrrrrrrs**
Hi @BusinessDuck 

I wanted to extend the Router class in a TypeScript project, but TypeScript doesn't recognize the methods of the base class because there were no TypeScript definitions.

### CODE REVIEW

**Comment by BusinessDuck** [comment]
Hi! Big Thanks. I think its take small time to rewrite in typescript, with auto generated definitions list, i'll do it asap

**Comment by BusinessDuck** [comment]
take a look at my current progress https://github.com/BusinessDuck/html5-history-router/tree/ts-migrate 

TODO: 
* migrate test and remove babel
* test && bugfix
* cleanup rm old deps

**Comment by Rogerrrrrrrs** [comment]
Thank you, that's awesome, I did not expect you to respond that quickly.

This looks good to me so far. Even though the `ts-migrate` branch did not work in my project out of the box for the following reasons:

 - The `.on` and `.always` methods have been changed to return a `Promise<boolean>` beacause of the `RouteHandler` type.
 - The type definition path `"types": "lib/router.d.ts",` is missing in `package.json`
 - The `RouterOptions` should be optional, otherwise you have to instantiate the router using `new Router({})`;

Once I changed these points my program worked exactly as before.

**Comment by BusinessDuck** [comment]
ts migrated in PR https://github.com/BusinessDuck/html5-history-router/pull/8

**Pull request closed without merging**
